import { CAPSULE } from "./capsule-v10-returned.js";
const core = await import("./hpr-runtime-core.js");
const rt = core.createRuntime(CAPSULE, null, { walkedFrom: "sandbox parity check — returned capsule" });
const r = await rt.handle("GET", "/api/verify", "");
const d = JSON.parse(r.body);
console.log("ok:", d.ok, "| verdict:", d.verdict);
console.log("digest:", d.digest);
console.log("records:", d.records, "| chain:", d.chain_length, "| writes:", d.writes);
console.log("ui_ok:", d.ui_ok, "| code_ok:", d.code_ok, "| engine:", d.engine_hash.slice(0,8));
const expected = "8fbaa547264d07f0ff07c2862d4c448312ea1be696f7eb5172eaaefa1d4a6009";
console.log(d.digest === expected ? "PARITY PASS — byte-identical to Node A live digest" : "PARITY FAIL");
const probe = await rt.handle("POST", "/api/record", JSON.stringify({body:"probe"}));
console.log("write probe:", probe.status, JSON.parse(probe.body).verdict);
